% Extract Individual Alpha Frequency (IAF) peak per subject
%
% This script loads feature.mat (generated by your EEG processing pipeline),
% locates an alpha-band peak per channel in the 7–14 Hz range, and summarizes
% a subject-level IAF (median across channels). Results are exported to CSV.
%
% Expected variables inside feature.mat:
%   - feature.name : cell array of filenames per subject
%   - feature.freqs or feature.f : vector of frequency bins (Hz)
%   - a spectrum field with dimensions [subjects x channels x freqs],
%     e.g., feature.spectrum, feature.psd, feature.PSD_full, feature.periodic_spectrum.
%     The script will try common names and pick the first that exists.
%
% If multiple spectrum fields are present, prefer an aperiodic-removed/periodic
% spectrum if available (e.g., periodic_spectrum). Otherwise, fallback to full PSD.

clear; clc;

% ------------------------- Configuration ---------------------------------
feature_mat_path = '/Volumes/NED_Backup3/COMBINED_Q1K_BC_2s/GENIAL/feature.mat';
alpha_band_hz = [7.5 12.5];     % match alpha range used in feature_extraction.m
smooth_window_hz = 0.5;         % smoothing window width in Hz (moving average)
min_channels_required = 3;      % require at least this many channel peaks per subject

out_path_external = '/Volumes/NED_Backup3/COMBINED_Q1K_BC_2s/GENIAL/alpha_peaks.csv';
out_path_local    = '/Users/emmanuelle.coutu-nadeau/Code/NED LAB/GENiAL/Data/EEG/GENIAL/RS-2s/alpha_peaks.csv';

% ---------------------------- Load data ----------------------------------
fprintf('Loading feature file: %s\n', feature_mat_path);
S = load(feature_mat_path);
if ~isfield(S, 'feature')
    error('feature.mat does not contain a variable named ''feature''.');
end
feature = S.feature;

% -------------------------------------------------------------------------
% Fast path: replicate Average_Alpha_Power but take MAX across channels
% Instead of mean(feature.PSD(:, :, 3), 2, 'omitnan'), compute the maximum
% across channels for the alpha band (index 3) per subject.
% -------------------------------------------------------------------------
if isfield(feature, 'PSD') && ndims(feature.PSD) == 3 && size(feature.PSD, 3) >= 3
    fprintf('Using feature.PSD(:, :, 3) to compute alpha power MAX across channels.\n');

    % Prepare SubjectID using same logic as elsewhere in this script
    if ~isfield(feature, 'name') || isempty(feature.name)
        error('feature.name not found; required to infer SubjectID.');
    end
    SubjectID = cell(size(feature.name));
    for i = 1:numel(feature.name)
        filename = feature.name{i};
        % Pattern for Q1K files: Q1K_HSJ_XXXX-YYYY_P_RSRio_... or Q1K_HSJ_XXXX-YYYY_P_RS_...
        q1k_pattern = '^(Q1K_HSJ_\d+-\d+_P)_((?i)RSRIO|RS)(?:_|$)';
        q1k_tokens = regexp(filename, q1k_pattern, 'tokens');
        % Pattern for BC files: BC_2017_XXXXX_YYYYYY_P_... -> extract BC_XXXXX
        bc_pattern = '^BC_2017_(\d{5})_';
        bc_tokens = regexp(filename, bc_pattern, 'tokens');
        if ~isempty(q1k_tokens)
            SubjectID{i} = q1k_tokens{1}{1};
        elseif ~isempty(bc_tokens)
            SubjectID{i} = ['BC_' bc_tokens{1}{1}];
        else
            % Fallback: try to extract subject part before RS/RSRio
            fallback_pattern = '^(.*?)_((?i)RSRIO|RS)(?:_|$)';
            fallback_tokens = regexp(filename, fallback_pattern, 'tokens');
            if ~isempty(fallback_tokens)
                SubjectID{i} = fallback_tokens{1}{1};
            else
                SubjectID{i} = filename; % use full filename if no pattern matches
            end
        end
    end

    alpha_idx = 3; % Alpha band slice in feature.PSD
    Palpha = squeeze(feature.PSD(:, :, alpha_idx)); % [subjects x channels]

    % Robust max across channels (ignore NaNs)
    Palpha_tmp = Palpha;
    Palpha_tmp(isnan(Palpha_tmp)) = -inf;
    [AlphaPower_MaxAcrossChannels, AlphaPower_MaxChannelIdx] = max(Palpha_tmp, [], 2);
    AlphaPower_MaxAcrossChannels(~isfinite(AlphaPower_MaxAcrossChannels)) = NaN;
    AlphaPower_MaxChannelIdx(~isfinite(AlphaPower_MaxAcrossChannels)) = NaN;

    T = table(SubjectID(:), AlphaPower_MaxAcrossChannels, AlphaPower_MaxChannelIdx, ...
        'VariableNames', {'SubjectID', 'AlphaPower_MaxAcrossChannels', 'AlphaPower_MaxChannelIdx'});

    % External export
    try
        writetable(T, out_path_external);
        fprintf('✅ Saved alpha power MAX across channels to (external): %s\n', out_path_external);
    catch ME
        fprintf('⚠️  Could not save external copy: %s\n', ME.message);
    end

    % Local project export
    local_dir = fileparts(out_path_local);
    if ~exist(local_dir, 'dir')
        mkdir(local_dir);
    end
    try
        writetable(T, out_path_local);
        fprintf('✅ Saved alpha power MAX across channels to (local): %s\n', out_path_local);
    catch ME
        fprintf('⚠️  Could not save local copy: %s\n', ME.message);
    end

    % Preview
    disp(head(T, 10));
    return; % Done via PSD fast path
end

% Frequency vector
freqs = [];
if isfield(feature, 'freqs'), freqs = feature.freqs; end
if isempty(freqs) && isfield(feature, 'f'), freqs = feature.f; end
% Try to pull from FOOOF results if present
if isempty(freqs) && isfield(feature, 'fooof_results_t')
    fr = feature.fooof_results_t;
    % fr may be a struct array or cell; try common patterns
    try
        if isstruct(fr) && isfield(fr, 'freqs') && ~isempty(fr(1).freqs)
            freqs = fr(1).freqs;
        elseif iscell(fr) && ~isempty(fr{1}) && isfield(fr{1}, 'freqs')
            freqs = fr{1}.freqs;
        end
    catch
        % leave empty; will error below if still empty
    end
end
if isempty(freqs)
    error('No frequency vector found (expected feature.freqs/feature.f or fooof_results_t.freqs).');
end
freqs = freqs(:)';

% Candidate spectrum field names (ordered by desirability)
candidates = {
    'fooofed_spectrum_t', ...       % aperiodic-removed spectrum (preferred)
    'periodic_component_t', ...     % periodic component from FOOOF
    'periodic_spectrum', ...        % other periodic spectrum naming
    'full_spectrum_t', ...          % full spectrum
    'pxx_t', ...                    % Welch PSD over time
    'PSD', ...                      % generic PSD cube
    'psd_spectrum', ...             % explicit PSD spectrum
    'power_spectrum', ...
    'PSD_full', ...                 % full PSD across freqs
    'psd'                           % fallback; ensure it is [sub x ch x f]
};

spec = [];
chosen_field = '';
for k = 1:numel(candidates)
    f = candidates{k};
    if isfield(feature, f)
        spec = feature.(f);
        chosen_field = f;
        break;
    end
end
if isempty(spec)
    error('Could not find a frequency-resolved spectrum field in feature.mat.');
end

% Dimensions check: [subjects x channels x freqs]
if ndims(spec) ~= 3 || size(spec, 3) ~= numel(freqs)
    error('Spectrum field %s must be [subjects x channels x freqs] matching frequency vector.', chosen_field);
end

fprintf('Using spectrum field: %s\n', chosen_field);
fprintf('Frequencies: %.2f–%.2f Hz (%d bins)\n', freqs(1), freqs(end), numel(freqs));

% ----------------------- Prepare identifiers -----------------------------
if ~isfield(feature, 'name') || isempty(feature.name)
    error('feature.name not found; required to infer SubjectID.');
end

SubjectID = cell(size(feature.name));
for i = 1:numel(feature.name)
    filename = feature.name{i};
    % Pattern for Q1K files: Q1K_HSJ_XXXX-YYYY_P_RSRio_... or Q1K_HSJ_XXXX-YYYY_P_RS_...
    q1k_pattern = '^(Q1K_HSJ_\d+-\d+_P)_((?i)RSRIO|RS)(?:_|$)';
    q1k_tokens = regexp(filename, q1k_pattern, 'tokens');
    % Pattern for BC files: BC_2017_XXXXX_YYYYYY_P_... -> extract BC_XXXXX
    bc_pattern = '^BC_2017_(\d{5})_';
    bc_tokens = regexp(filename, bc_pattern, 'tokens');
    if ~isempty(q1k_tokens)
        SubjectID{i} = q1k_tokens{1}{1};
    elseif ~isempty(bc_tokens)
        SubjectID{i} = ['BC_' bc_tokens{1}{1}];
    else
        % Fallback: try to extract subject part before RS/RSRio
        fallback_pattern = '^(.*?)_((?i)RSRIO|RS)(?:_|$)';
        fallback_tokens = regexp(filename, fallback_pattern, 'tokens');
        if ~isempty(fallback_tokens)
            SubjectID{i} = fallback_tokens{1}{1};
        else
            SubjectID{i} = filename; % use full filename if no pattern matches
        end
    end
end

% --------------------- Alpha peak per channel ----------------------------
% Build smoothing window length (in bins)
df = median(diff(freqs));
if isnan(df) || df <= 0
    df = (freqs(end) - freqs(1)) / max(1, numel(freqs)-1);
end
win_bins = max(1, round(smooth_window_hz / df));

alpha_idx = freqs >= alpha_band_hz(1) & freqs <= alpha_band_hz(2);
if ~any(alpha_idx)
    error('Alpha band range does not overlap with frequency vector.');
end

nSub = size(spec, 1);
nChan = size(spec, 2);

IAF_per_sub = nan(nSub, 1);
IAF_strength = nan(nSub, 1); % peak height (arbitrary units)

for s = 1:nSub
    chan_peaks = nan(nChan, 1);
    chan_heights = nan(nChan, 1);
    for c = 1:nChan
        P = squeeze(spec(s, c, :));
        P = P(:)';
        % Robustify to strictly positive before log10
        P = max(P, eps);
        % Smooth spectrum (optional)
        if win_bins > 1
            Psm = movmean(P, win_bins);
        else
            Psm = P;
        end
        % Work in log-power for peak definition stability
        logP = log10(Psm);
        seg = logP(alpha_idx);
        fseg = freqs(alpha_idx);
        if all(~isfinite(seg)) || numel(seg) < 3
            continue;
        end
        % Find local maximum within alpha segment
        [pk, loc] = max(seg);
        if isfinite(pk)
            chan_peaks(c) = fseg(loc);
            chan_heights(c) = pk;
        end
    end
    % Aggregate per subject
    valid = isfinite(chan_peaks);
    if sum(valid) >= min_channels_required
        IAF_per_sub(s) = median(chan_peaks(valid));
        IAF_strength(s) = median(chan_heights(valid));
    else
        IAF_per_sub(s) = NaN;
        IAF_strength(s) = NaN;
    end
end

% --------------------------- Export table --------------------------------
T = table(SubjectID(:), IAF_per_sub, IAF_strength, ...
    'VariableNames', {'SubjectID', 'IAF_Hz', 'IAF_logPower'});

fprintf('\nComputed IAF for %d subjects (%.0f with valid peaks)\n', ...
    nSub, sum(isfinite(T.IAF_Hz)));

% External export
try
    writetable(T, out_path_external);
    fprintf('✅ Saved alpha peaks to (external): %s\n', out_path_external);
catch ME
    fprintf('⚠️  Could not save external copy: %s\n', ME.message);
end

% Local project export
local_dir = fileparts(out_path_local);
if ~exist(local_dir, 'dir')
    mkdir(local_dir);
end
try
    writetable(T, out_path_local);
    fprintf('✅ Saved alpha peaks to (local): %s\n', out_path_local);
catch ME
    fprintf('⚠️  Could not save local copy: %s\n', ME.message);
end

% Preview
disp(head(T, 10));


